### ISSUE TITLE
cann't read lombok annotation

### ISSUE THREAD

**Issue by chxbca** [JetBrains/Qodana#12]

**Comment by a-kuznetsova** [comment]
Hello @chxbca ,
Thank you for reporting this. I have created an issue [QD-644](https://youtrack.jetbrains.com/issue/QD-644).

**Comment by SulaymonHursanov** [comment]
@a-kuznetsova, we are still waiting (if u are contributor of this project please fix it!)

**Comment by a-kuznetsova** [comment]
Hi @chxbca and @SulaymonHursanov,

Lombok plugin was added to Qodana some time ago. However, there are still some issues to be resolved(for example [QD-751](https://youtrack.jetbrains.com/issue/QD-751)). 

Please be informed that the Github Issues section in this repository will be disabled as of April 6, 2021. If you would like to be notified about the issue updates, add yourself as a watcher for the issue [QD-751](https://youtrack.jetbrains.com/issue/QD-751).
