### ISSUE TITLE
Optimize how qodana is creating result-allProblems.json

### ISSUE THREAD

**Issue by oleg-andreyev** [JetBrains/Qodana#18]
If the project has a lot of issues this file could be very-very big >120M
It would be awesome to split this file into chunks.

This "main" file JSON would have locations to other chunks and later it could be downloaded in parallel.
![image](https://user-images.githubusercontent.com/1244112/107496404-f0db3c00-6b99-11eb-9624-3dc4fe43cc71.png)

**Comment by a-kuznetsova** [comment]
Hi @oleg-andreyev,

Thank you for your feedback regarding the `result-allProblems.json` file. I have created an issue [QD-696](https://youtrack.jetbrains.com/issue/QD-696).

**Comment by a-kuznetsova** [comment]
Hi @oleg-andreyev,

Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021.
I am closing this issue because it is available in YouTrack.
