### ISSUE TITLE
Document performance tips on second run of Qodana

### ISSUE THREAD

**Issue by oleg-andreyev** [JetBrains/Qodana#19]
This is something we've done locally for Qodana and I'm willing to share this information:

# First, run
- Mount /root/.cache into Qodana container
- Execute the first clean run of Qodana (--save-report), first run will be very slow because IDEA needs to index everything and - parse everything
- After a successful run, run archivation of the idea folder, which is located in a folder that was mounted to /root/.cache, and save artifact into shared-storage (in our case it's minio)
 
# Second run
- Download artifact and unpack it, you should have an "idea" folder
- Mount /root/.cache into Qodana container
- Second run will be much faster as IDEA has a cache and does not need to index/parse everything again

Ref.: https://youtrack.jetbrains.com/issue/QD-697

**Comment by a-kuznetsova** [comment]
Hi @oleg-andreyev,

Thank you for sharing your tips!
Starting from version `v2021.1.17-eap` Qodana supports `--cache-dir` argument. Please find more information [here](https://github.com/JetBrains/Qodana/tree/main/Docker).

Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021. Contact us at [qodana-support@jetbrains.com](mailto:qodana-support@jetbrains.com) or via [our issue tracker](https://youtrack.jetbrains.com/newIssue?project=QD). We are eager to receive your feedback on the existing Qodana functionality and learn what other features you miss in it.
