### ISSUE TITLE
Qodana for Azure Devops

### ISSUE THREAD

**Issue by marian-craciunescu** [JetBrains/Qodana#22]
It would be great to also have codana in Azure Devops

**Comment by a-kuznetsova** [comment]
Hi @marian-craciunescu,

Thank you for reporting this!

I have created an issue [QD-776](https://youtrack.jetbrains.com/issue/QD-776) in our issue tracker. We will consider support for Azure Devops. 

Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021.
If you would like to be notified about the issue updates, add yourself as a watcher for the issue [QD-776](https://youtrack.jetbrains.com/issue/QD-776).
