### ISSUE TITLE
Kotlin multiplatform projects support

### ISSUE THREAD

**Issue by Alex009** [JetBrains/Qodana#23]
Thanks for cool tool! but for my purposes now it seems bugged.

i got simple multiplatform project - https://github.com/icerockdev/moko-parcelize
and run qodana by docker.
```
git clone https://github.com/icerockdev/moko-parcelize.git
cd moko-parcelize
docker run --rm -it -v $(pwd):/data/project/ -p 8080:8080 jetbrains/qodana --show-report
```
and after 10 minutes got results:
![image](https://user-images.githubusercontent.com/5010169/107763919-e66b9e80-6d61-11eb-873c-4b82bbaaca79.png)
these errors is invalid - inspections cant see dependencies. 
[Qodana.htm.zip](https://github.com/JetBrains/Qodana/files/5971490/Qodana.htm.zip)

also for speed up analisis how can we use cache of .gradle dependencies?

**Comment by a-kuznetsova** [comment]
Hi @Alex009,

Thank you for your question. 
At the moment Qodana supports only Kotlin for Server Side. I have updated the Qodana documentation to clarify [supported languages and technologies](https://github.com/JetBrains/Qodana/blob/main/General/supported-technologies.md).

We plan to [support Kotlin Multiplatform](https://youtrack.jetbrains.com/issue/QD-710) in the near future.

**Comment by a-kuznetsova** [comment]
Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021.
If you would like to be notified about the issue updates, add yourself as a watcher for the issue [QD-710: support Kotlin Multiplatform](https://youtrack.jetbrains.com/issue/QD-710).
