### ISSUE TITLE
sarif support in GitHub Actions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/Qodana#30]
Is it possible to generate a sarif file and upload it with CodeQL action?

**Comment by a-kuznetsova** [comment]
Hi @JavierSegoviaCordoba,

We plan to add support for SARIF format in the near future.

Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021. Contact us at [qodana-support@jetbrains.com](mailto:qodana-support@jetbrains.com) or via [our issue tracker](https://youtrack.jetbrains.com/newIssue?project=QD). We are eager to receive your feedback on the existing Qodana functionality and learn what other features you miss in it.
