### ISSUE TITLE
Provide IntelliJ formatting check

### ISSUE THREAD

**Issue by leonard84** [JetBrains/Qodana#31]
Hi,

since Qodana is built on top of IntelliJ, would it be possible to use it to check that source code conforms to the IntelliJ formatter settings? Currently, there is no standardized way to enforce formatting based on the IntelliJ formatter, and since there are subtle differences between its and Eclipses formatter, you can't just use [spotless](https://github.com/diffplug/spotless/) to do this.

See also https://youtrack.jetbrains.com/issue/IDEA-185010

**Comment by a-kuznetsova** [comment]
Hi @leonard84,

Thank you for reporting this. I have created an issue [QD-774](https://youtrack.jetbrains.com/issue/QD-774) in our issue tracker.

Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021.
If you would like to be notified about the issue updates, add yourself as a watcher for the issue [QD-774](https://youtrack.jetbrains.com/issue/QD-774).
