### ISSUE TITLE
Feature Request: Jenkins Support

### ISSUE THREAD

**Issue by litan1106** [JetBrains/Qodana#9]

**Comment by a-kuznetsova** [comment]
Thank you for your feature request. 
At this time, we do not currently have a plan to add support for Jenkins. However, I think you could integrate our [Qodana Docker image](https://github.com/JetBrains/Qodana/tree/main/Docker) into your Jenkins pipeline.

**Comment by litan1106** [comment]
> Thank you for your feature request.
> At this time, we do not currently have a plan to add support for Jenkins. However, I think you could integrate our [Qodana Docker image](https://github.com/JetBrains/Qodana/tree/main/Docker) into your Jenkins pipeline.

Thanks. Do you have any general instructions for Qodana on Jenkins?
